### ISSUE TITLE
Image is only "attached" but is not shown

### ISSUE THREAD

**Issue by HeroHann** [Pustur/whatsapp-chat-parser-website#25]
Hello,
I am glad I fund this project as it is the first that is working as intended...mostly.

When importing either a zip or only the .txt file I get the massage, that the pictures are "2015-08-04-PHOTO-00004762.jpg <‎attached>". It looks like in my case the image (which is in the same folder) is treated like a text message.
Any way to change that? I can send an example your way if needed. The export I am using is rather old (2017) the layout of the .txt has changed since. Any way to (I guess this is the problem) support older versions aswell?
Thanks!

**Comment by Pustur** [comment]
Hi @HeroHann, thanks for the report. 

I think that the problem is easily solved by modifying the regex to detect attachments. I'll work on it whenever I have some spare time.

**Comment by HeroHann** [comment]
Thanks! If you need any examplefile just comment here👍

**Comment by Pustur** [comment]
Hi @HeroHann,

Can you check if using this updated version of the website fixes your problem?  
https://fix-attachment-parser--whatsapp-chat-parser.netlify.app/

Remember that for the files to show up you have to upload a `.zip` file. `.txt` files won't show the attachments.

Thanks in advance

**Comment by HeroHann** [comment]
Hello,
the fix works perfect! Thanks!
I will mark this as solved….

**Comment by HeroHann** [comment]
The same problem is back again even when using the version from the link…

**Comment by HeroHann** [comment]
Here you go with a example: https://pixeldrain.com/u/6xWtpyx6
When opening via the txt it just shows the attachement as text. When opening via the .zip it shows „error not found“.

**Comment by Pustur** [comment]
It seems this is the same situation as https://github.com/Pustur/whatsapp-chat-parser-website/issues/21

The zip file contains a folder so it can't find the files. Are you sure you are using an export from whatsapp directly or are you modifying it?

**Comment by HeroHann** [comment]
Yes you are right🙈 Sorry!

**Comment by Pustur** [comment]
Hey @HeroHann, 

Just a heads up, I released a new version in the main website that includes the newest parser version.  
You should be able to use this link from now on: https://whatsapp-chat-parser.netlify.app/

I will remove the other temporary link
